service: notes-app-api

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  environment:
    tableName: notes
    stripeSecretKey: ${env:STRIPE_SECRET_KEY}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-west-1:*:*"

resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}

functions:
  create:
    handler: handlers/create.main
    events:
      - http:
          path: /notes
          method: post
          cors: true
          authorizer: aws_iam
  get:
    handler: handlers/get.main
    events:
      - http:
          path: /notes/{id}
          method: get
          cors: true
          authorizer: aws_iam
  list:
    handler: handlers/list.main
    events:
      - http:
          path: /notes
          method: get
          cors: true
          authorizer: aws_iam
  update:
    handler: handlers/update.main
    events:
      - http:
          path: notes/{id}
          method: put
          cors: true
          authorizer: aws_iam
  delete:
    handler: handlers/delete.main
    events:
      - http:
          path: notes/{id}
          method: delete
          cors: true
          authorizer: aws_iam
  billing:
    handler: handlers/billing.main
    events:
      - http:
          path: /billing
          method: post
          cors: true
          authorizer: aws_iam
